### PR TITLE
filled out PaymentController.cs.

### PR DESCRIPTION
**Pull request by flawavi**
test: 

1. checkout fw-fixPaymentController
2. make sure there is no mention of BangazonDbContext, and that instead there is User_AuthenticationDbContext
3. There will be some red squiggles related to active user and the view models. That's okay for now.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
lgtm

**Comment by davidyunker** [comment]
Just needs the change to the namespace.

**Comment by ewilliamswtn** [comment]
👍 all the namespace

**Comment by estorms** [comment]
lgtm

**Pull request merged**
