### PR TITLE
elements on the layout changed

### PR DESCRIPTION
**Pull request by lairdhousehold**
## ToTest:
git fetch 
git checkout 
## Details
The layout has been modified to show and link the following items the bangazon product list, sell a product, and product types.

### CODE REVIEW

**Comment by flawavi** [comment]
WOMMY, ORIGAMI

**Comment by ewilliamswtn** [comment]
womm y'all

**Comment by estorms** [comment]
LGTM!

**Comment by davidyunker** [comment]
womm

**Pull request merged**
