### PR TITLE
database seeding successfully

### PR DESCRIPTION
**Pull request by estorms**
Details:

Database now seeds as it should.

To test:

1. Git fetch
2. Git checkout es-database-seeding
3. Run the program and be sure that the database seeds with the types listed in the dbinitalizer file. You can test this by selecting "Product Types" from the navbar and/or manually reviewing your database in the `SQL Server Object Explorer`

Note: Some code in the `Product` controller and `Product Type` view has been commented out b/c it references products, which we don't yet have in our database.

### CODE REVIEW

**Comment by davidyunker** [comment]
ERMERGERD DROPDOWN WOMMY

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍  af

**Comment by flawavi** [comment]
GO GO GO

**Pull request merged**
