### PR TITLE
changed the route and the associated controller so that user remains …

### PR DESCRIPTION
**Pull request by flawavi**
…on product list page upon logout. removed the HomeController because we never used it.

To Test:

1. git checkout fw-login
2. login as any user and make sure  you are immediately taken to the product list page.
3. logout and make sure you remain on the product list page, or are redirected there if you are not currently on it.

### CODE REVIEW

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
WOMM

**Comment by flawavi** [comment]
WE BE WOMMIN

**Comment by estorms** [comment]
Implicit womm

**Comment by ewilliamswtn** [comment]
👍

**Pull request merged**
