### PR TITLE
Es user registration

### PR DESCRIPTION
**Pull request by estorms**
Details:

Migrations were updated in kick-ass prior branch (dy-migrations) so database now includes the following tables: Product, ProductType, ProductTypeSubCategory, Order, LineItem, PaymentType.

User can also register for an account by submitting email, password, first name, last name, and street address.

To test:

1. Git fetch
2. Git checkout es-user-registration
3. If necessary, apply migrations to update your database
4. Register for an account and be sure the site routes you back to the homepage, with your username included in the welcome message on the upper-right corner.

### CODE REVIEW

**Comment by davidyunker** [comment]
WOMM

**Comment by flawavi** [comment]
WOMMY, TOMMY

**Comment by ewilliamswtn** [comment]
womm af

**Comment by lairdhousehold** [comment]
WOMM

**Pull request merged**
