### PR TITLE
added controllers from previous project

### PR DESCRIPTION
**Pull request by davidyunker**
TO TEST:
git fetch 
git checkout dy-importOldFiles 

you should have the following files added: CustomerController.cs, OrderController.cs, PaymentController.cs,  ProductsController.cs

### CODE REVIEW

**Comment by estorms** [comment]
LGTM!

**Comment by lairdhousehold** [comment]
lgtm

**Comment by ewilliamswtn** [comment]
👍    // also, wtf is that emoji 👈

**Comment by flawavi** [comment]
lgtm

**Pull request merged**
