### PR TITLE
touched new razor files for products and debugged.

### PR DESCRIPTION
**Pull request by flawavi**
To Test:

git fetch
git checkout fw-portProductsViews

Make sure that the following files have been added, and that there are no red squiggles:
1. Create.cshtml
2. Detail.cshtml
3. Index.cshtml
4. Type.cshtml
5. Types.cshtml

### CODE REVIEW

**Comment by estorms** [comment]
lgtm!

**Comment by ewilliamswtn** [comment]
waf

**Comment by estorms** [comment]
LGTM

**Comment by lairdhousehold** [comment]
lgtm

**Comment by davidyunker** [comment]
lgtm

**Pull request merged**
