### PR TITLE
Ew payment view

### PR DESCRIPTION
**Pull request by ewilliamswtn**
## Changelog
- Pulled over ```Views/Payment/Create.cshtml``` from old project
- Adjusted namespace reference accordingly

## To Test
- ```git fetch```
- ```git checkout ew-payment-view```
- run app
- once your browser has navigated to the **Bangazon!** home page, type http://localhost:5000/payment/create into navigation bar, or click link provided
- verify payment form is displayed

### CODE REVIEW

**Comment by estorms** [comment]
womm!

**Comment by flawavi** [comment]
WOMMY, SALAMI

**Comment by lairdhousehold** [comment]
womm

**Comment by davidyunker** [comment]
womm

**Pull request merged**
