### PR TITLE
added JS logic to the site.js file

### PR DESCRIPTION
**Pull request by davidyunker**
git fetch 
git checkout dy-JS 

Login 
Click Sell A Product. 
Fill out the fields. 
Choose the dropdown and hit create.
It should create your product. 

Added features:
	can no longer sell a product/see product types unless you are logged in, now only one Bangazon in the navbar, localhost now defaults to products index view. 

	Product Detail view now works

	can now add items to a cart, add payment and submit order

### CODE REVIEW

**Comment by estorms** [comment]
WOMM AllDAYLONG

**Comment by lairdhousehold** [comment]
big dry stanky womm

**Comment by flawavi** [comment]
STRWOMM THURMAN

**Comment by davidyunker** [comment]
Self-WOMM

**Comment by lairdhousehold** [comment]
womm

**Comment by ewilliamswtn** [comment]
👍 👍 👍

**Pull request merged**
